config/routes.rb
Lama::Application.routes.draw do
  resources :map_states

  resources :geometry_marks

  resources :polygon_marks
  resources :point_marks
  resources :layers

  get "home/index"

   root :to => 'home#index'

end

app/models/map_state.rb
class MapState < ActiveRecord::Base
end

app/controllers/map_states_controller.rb
class MapStatesController < ApplicationController
  # GET /map_states
  # GET /map_states.json
  def index
    @map_states = MapState.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @map_states }
    end
  end

  # GET /map_states/1
  # GET /map_states/1.json
  def show
    @map_state = MapState.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @map_state }
    end
  end

  # GET /map_states/new
  # GET /map_states/new.json
  def new
    @map_state = MapState.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @map_state }
    end
  end

  # GET /map_states/1/edit
  def edit
    @map_state = MapState.find(params[:id])
  end

  # POST /map_states
  # POST /map_states.json
  def create
    @map_state = MapState.new(params[:map_state])

    respond_to do |format|
      if @map_state.save
        format.html { redirect_to @map_state, :notice => 'Map state was successfully created.' }
        format.json { render :json => @map_state, :status => :created, :location => @map_state }
      else
        format.html { render :action => "new" }
        format.json { render :json => @map_state.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /map_states/1
  # PUT /map_states/1.json
  def update
    @map_state = MapState.find(params[:id])

    respond_to do |format|
      if @map_state.update_attributes(params[:map_state])
        format.html { redirect_to @map_state, :notice => 'Map state was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @map_state.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /map_states/1
  # DELETE /map_states/1.json
  def destroy
    @map_state = MapState.find(params[:id])
    @map_state.destroy

    respond_to do |format|
      format.html { redirect_to map_states_url }
      format.json { head :ok }
    end
  end
end

app/helpers/map_states_helper.rb
module MapStatesHelper
end

app/views/map_states/_form.html.erb
<%= form_for(@map_state) do |f| %>
  <% if @map_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map_state.errors.count, "error") %> prohibited this map_state from being saved:</h2>

      <ul>
      <% @map_state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.text_field :zoom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map_states/edit.html.erb
<h1>Editing map_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @map_state %> |
<%= link_to 'Back', map_states_path %>

app/views/map_states/index.html.erb
<h1>Listing map_states</h1>

<table>
  <tr>
    <th>X</th>
    <th>Y</th>
    <th>Zoom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @map_states.each do |map_state| %>
  <tr>
    <td><%= map_state.x %></td>
    <td><%= map_state.y %></td>
    <td><%= map_state.zoom %></td>
    <td><%= link_to 'Show', map_state %></td>
    <td><%= link_to 'Edit', edit_map_state_path(map_state) %></td>
    <td><%= link_to 'Destroy', map_state, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map state', new_map_state_path %>

app/views/map_states/new.html.erb
<h1>New map_state</h1>

<%= render 'form' %>

<%= link_to 'Back', map_states_path %>

app/views/map_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>X:</b>
  <%= @map_state.x %>
</p>

<p>
  <b>Y:</b>
  <%= @map_state.y %>
</p>

<p>
  <b>Zoom:</b>
  <%= @map_state.zoom %>
</p>


<%= link_to 'Edit', edit_map_state_path(@map_state) %> |
<%= link_to 'Back', map_states_path %>