config/routes.rb
Lama::Application.routes.draw do
  resources :map_states

  resources :geometry_marks

  resources :polygon_marks
  resources :point_marks
  resources :layers

  get "home/index"

   root :to => 'home#index'

end

app/models/geometry_mark.rb
class GeometryMark < ActiveRecord::Base
end

app/controllers/geometry_marks_controller.rb
class GeometryMarksController < ApplicationController
  # GET /geometry_marks
  # GET /geometry_marks.json
  def index
    @geometry_marks = GeometryMark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @geometry_marks }
    end
  end

  # GET /geometry_marks/1
  # GET /geometry_marks/1.json
  def show
    @geometry_mark = GeometryMark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @geometry_mark }
    end
  end

  # GET /geometry_marks/new
  # GET /geometry_marks/new.json
  def new
    @geometry_mark = GeometryMark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @geometry_mark }
    end
  end

  # GET /geometry_marks/1/edit
  def edit
    @geometry_mark = GeometryMark.find(params[:id])
  end

  # POST /geometry_marks
  # POST /geometry_marks.json
  def create
    @geometry_mark = GeometryMark.new(params[:geometry_mark])

    respond_to do |format|
      if @geometry_mark.save
        ewkt = "SRID=4269;" + params[:wkt]
        @geometry_mark.the_geom = Geometry.from_ewkt(ewkt)
        @geometry_mark.save!
        format.html { redirect_to @geometry_mark, :notice => 'Geometry mark was successfully created.' }
        format.json { render :json => @geometry_mark, :status => :created, :location => @geometry_mark }
      else
        format.html { render :action => "new" }
        format.json { render :json => @geometry_mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /geometry_marks/1
  # PUT /geometry_marks/1.json
  def update
    @geometry_mark = GeometryMark.find(params[:id])

    respond_to do |format|
      if @geometry_mark.update_attributes(params[:geometry_mark])
        ewkt = "SRID=4269;" + params[:wkt]
        @geometry_mark.the_geom = Geometry.from_ewkt(ewkt)
        @geometry_mark.save!
        format.html { redirect_to @geometry_mark, :notice => 'Geometry mark was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @geometry_mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /geometry_marks/1
  # DELETE /geometry_marks/1.json
  def destroy
    @geometry_mark = GeometryMark.find(params[:id])
    @geometry_mark.destroy

    respond_to do |format|
      format.html { redirect_to geometry_marks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/geometry_marks_helper.rb
module GeometryMarksHelper
end

app/views/geometry_marks/_form.html.erb
<%= form_for(@geometry_mark) do |f| %>
  <% if @geometry_mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geometry_mark.errors.count, "error") %> prohibited this geometry_mark from being saved:</h2>

      <ul>
      <% @geometry_mark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :radius %><br />
    <%= f.text_field :radius %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/geometry_marks/edit.html.erb
<h1>Editing geometry_mark</h1>

<%= render 'form' %>

<%= link_to 'Show', @geometry_mark %> |
<%= link_to 'Back', geometry_marks_path %>

app/views/geometry_marks/index.html.erb
<h1>Listing geometry_marks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Radius</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @geometry_marks.each do |geometry_mark| %>
  <tr>
    <td><%= geometry_mark.name %></td>
    <td><%= geometry_mark.radius %></td>
    <td><%= link_to 'Show', geometry_mark %></td>
    <td><%= link_to 'Edit', edit_geometry_mark_path(geometry_mark) %></td>
    <td><%= link_to 'Destroy', geometry_mark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Geometry mark', new_geometry_mark_path %>

app/views/geometry_marks/new.html.erb
<h1>New geometry_mark</h1>

<%= render 'form' %>

<%= link_to 'Back', geometry_marks_path %>

app/views/geometry_marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @geometry_mark.name %>
</p>

<p>
  <b>Radius:</b>
  <%= @geometry_mark.radius %>
</p>


<%= link_to 'Edit', edit_geometry_mark_path(@geometry_mark) %> |
<%= link_to 'Back', geometry_marks_path %>