config/routes.rb
Lama::Application.routes.draw do
  resources :map_states

  resources :geometry_marks

  resources :polygon_marks
  resources :point_marks
  resources :layers

  get "home/index"

   root :to => 'home#index'

end

app/models/layer.rb
class Layer < ActiveRecord::Base
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  # GET /layers
  # GET /layers.json
  def index
    @layers = Layer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @layers }
    end
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
    @layer = Layer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @layer }
    end
  end

  # GET /layers/new
  # GET /layers/new.json
  def new
    @layer = Layer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @layer }
    end
  end

  # GET /edit/1/edit
  def edit
    @layer = Layer.find(params[:id])
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(:name => params[:name], :colour => params[:colour])

    respond_to do |format|
      if @layer.save
        @layer.save!
        format.html { redirect_to @layer, :notice => 'Layer was successfully created.' }
        format.json { render :json => @layer, :status => :created, :location => @layer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @layer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /layers/1
  # PUT /layers/1.json
  def update
    @layer = Layer.find(params[:id])

    respond_to do |format|
      if @layer.update_attributes(:name => params[:name], :colour => params[:colour])
        @layer.save!
        format.html { redirect_to @layer, :notice => 'Layer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @layer.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer = Layer.find(params[:id])
    @layer.destroy

    respond_to do |format|
      format.html { redirect_to layers_url }
      format.json { head :ok }
    end
  end

end

app/helpers/layer_helper.rb
module LayerHelper
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.erb
<%= form_for(@layer) do |f| %>
  <% if @layer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@layer.errors.count, "error") %> prohibited this layer from being saved:</h2>

      <ul>
      <% @layer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :colour %><br />
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<h1>Editing layer</h1>

<%= render 'form' %>

<%= link_to 'Show', @layer %> |
<%= link_to 'Back', layers_path %>

app/views/layers/index.html.erb
<h1>Listing layers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @layers.each do |layer| %>
  <tr>
    <td><%= layer.name %></td>
    <td><%= link_to 'Show', layer %></td>
    <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
    <td><%= link_to 'Destroy', layer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Layer', new_layer_path %>

app/views/layers/new.html.erb
<h1>New layer</h1>

<%= render 'form' %>

<%= link_to 'Back', layers_path %>

app/views/layers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @layer.name %>
</p>

<p>
  <b>Colour:</b>
  <%= @layer.colour %>
</p>



<%= link_to 'Edit', edit_layer_path(@layer) %> |
<%= link_to 'Back', layers_path %>