config/routes.rb
Lama::Application.routes.draw do
  resources :map_states

  resources :geometry_marks

  resources :polygon_marks
  resources :point_marks
  resources :layers

  get "home/index"

   root :to => 'home#index'

end

app/models/point_mark.rb
class PointMark < ActiveRecord::Base
end

app/controllers/point_marks_controller.rb
class PointMarksController < ApplicationController
  # GET /point_marks
  # GET /point_marks.json
  def index
    @point_marks = PointMark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @point_marks }
    end
  end

  # GET /point_marks/1
  # GET /point_marks/1.json
  def show
    @point_mark = PointMark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @point_mark }
    end
  end

  # GET /point_marks/new
  # GET /point_marks/new.json
  def new
    @point_mark = PointMark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @point_mark }
    end
  end

  # GET /point_marks/1/edit
  def edit
    @point_mark = PointMark.find(params[:id])
  end

  # POST /point_marks
  # POST /point_marks.json
  def create
    @point_mark = PointMark.new(:name => params[:name])

    respond_to do |format|
      if @point_mark.save
	@point_mark.the_geom = Point.from_x_y(params[:x], params[:y], 4269)
	@point_mark.save!
        format.html { redirect_to @point_mark, :notice => 'Point mark was successfully created.' }
        format.json { render :json => @point_mark, :status => :created, :location => @point_mark }
      else
        format.html { render :action => "new" }
        format.json { render :json => @point_mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /point_marks/1
  # PUT /point_marks/1.json
  def update
    @point_mark = PointMark.find(params[:id])

    respond_to do |format|
      if @point_mark.update_attributes(:name => params[:name])
	@point_mark.the_geom = Point.from_x_y(params[:x], params[:y], 4269)
	@point_mark.save!
        format.html { redirect_to @point_mark, :notice => 'Point mark was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @point_mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /point_marks/1
  # DELETE /point_marks/1.json
  def destroy
    @point_mark = PointMark.find(params[:id])
    @point_mark.destroy

    respond_to do |format|
      format.html { redirect_to point_marks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/point_marks_helper.rb
module PointMarksHelper
end

app/views/point_marks/_form.html.erb
<%= form_for(@point_mark) do |f| %>
  <% if @point_mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point_mark.errors.count, "error") %> prohibited this point_mark from being saved:</h2>

      <ul>
      <% @point_mark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/point_marks/edit.html.erb
<h1>Editing point_mark</h1>

<%= render 'form' %>

<%= link_to 'Show', @point_mark %> |
<%= link_to 'Back', point_marks_path %>

app/views/point_marks/index.html.erb
<h1>Listing point_marks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @point_marks.each do |point_mark| %>
  <tr>
    <td><%= point_mark.name %></td>
    <td><%= link_to 'Show', point_mark %></td>
    <td><%= link_to 'Edit', edit_point_mark_path(point_mark) %></td>
    <td><%= link_to 'Destroy', point_mark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Point mark', new_point_mark_path %>

app/views/point_marks/new.html.erb
<h1>New point_mark</h1>

<%= render 'form' %>

<%= link_to 'Back', point_marks_path %>

app/views/point_marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @point_mark.name %>
</p>


<%= link_to 'Edit', edit_point_mark_path(@point_mark) %> |
<%= link_to 'Back', point_marks_path %>